/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
    nodes: {
        Head: THREE.Mesh
        Barrel007: THREE.Mesh
        Barrel007_1: THREE.Mesh
        Body: THREE.Mesh
        Tracks007: THREE.Mesh
        Tracks007_1: THREE.Mesh
        Tracks007_2: THREE.Mesh
    }
    materials: {
        ['BodyMetallic.007']: THREE.MeshStandardMaterial
        ['TracksDark.008']: THREE.MeshStandardMaterial
        ['BodyFlat.007']: THREE.MeshStandardMaterial
    }
}

type PlayerTankProps = JSX.IntrinsicElements['group'] & {
    headDirection?: [number, number, number];
    bodyDirection?: [number, number, number];
    playerColor?: string; // Optional color for BodyFlat material
};


export function PlayerTank({
    headDirection = [-Math.PI, 0, -Math.PI], // Default rotation
    bodyDirection = [0, 0, -Math.PI], // Default rotation
    playerColor = '#D1BDFF', // Default BodyFlat color
    ...props
}: PlayerTankProps) {
    const { nodes, materials } = useGLTF('/models/PlayerTank.glb') as GLTFResult;

    materials['BodyFlat.007'].color = new THREE.Color(playerColor);
    materials['BodyMetallic.007'].color = new THREE.Color(playerColor);

    return (
        <group {...props} dispose={null}>
            <group name="Scene">
                <mesh
                    name="Head"
                    castShadow
                    receiveShadow
                    geometry={nodes.Head.geometry}
                    material={materials['BodyMetallic.007']}
                    position={[0, 0.164, 0]}
                    rotation={headDirection}
                    scale={[0.098, 0.061, 0.098]}
                    userData={{ name: 'Head' }}>
                    <group
                        name="Barrel"
                        position={[0, -0.372, 0.939]}
                        rotation={[-Math.PI, 0, -Math.PI]}
                        scale={[-0.144, -0.233, -0.144]}
                        userData={{ name: 'Barrel' }}>
                        <mesh
                            name="Barrel007"
                            castShadow
                            receiveShadow
                            geometry={nodes.Barrel007.geometry}
                            material={materials['BodyMetallic.007']}
                        />
                        <mesh
                            name="Barrel007_1"
                            castShadow
                            receiveShadow
                            geometry={nodes.Barrel007_1.geometry}
                            material={materials['TracksDark.008']}
                        />
                    </group>
                </mesh>
                <mesh
                    name="Body"
                    castShadow
                    receiveShadow
                    geometry={nodes.Body.geometry}
                    material={materials['BodyFlat.007']}
                    rotation={bodyDirection}
                    scale={[-0.13, -0.052, -0.17]}
                    userData={{ name: 'Body' }}>
                    <group name="Tracks" scale={[1.3, 0.952, 0.952]} userData={{ name: 'Tracks' }}>
                        <mesh
                            name="Tracks007"
                            castShadow
                            receiveShadow
                            geometry={nodes.Tracks007.geometry}
                            material={materials['BodyFlat.007']}
                        />
                        <mesh
                            name="Tracks007_1"
                            castShadow
                            receiveShadow
                            geometry={nodes.Tracks007_1.geometry}
                            material={materials['BodyMetallic.007']}
                        />
                        <mesh
                            name="Tracks007_2"
                            castShadow
                            receiveShadow
                            geometry={nodes.Tracks007_2.geometry}
                            material={materials['TracksDark.008']}
                        />
                    </group>
                </mesh>
            </group>
        </group>
    )
}

useGLTF.preload('/models/PlayerTank.glb')

